### ISSUE TITLE
Image Upload 

### ISSUE THREAD

**Issue by Meistercoach83** [meanjs/mean#1030]
Hi,
I tried to use the new image upload with the config in config/env/local.js:

    'use strict';
    module.exports = {
      uploads: {
        locationCategoryPicture:{
          dest: './modules/locationCategories/client/img/uploads', //  upload destination path
          limits: {
            fileSize: 1 * 1024 * 1024 // Max file size in bytes (1 MB)
          }
        }
      }
    };

my route:

    app.route('/api/locationCategories/picture/:locationCategoryId').post(locationCategories.changeProfilePicture);

server.js:
    
    exports.changeProfilePicture = function (req, res) {
      var locationCategory = req.locationCategory;
      var upload = multer(config.uploads.locationCategoryPicture).single('newLocationCategoryPicture');
      var locationCategoryUploadFileFilter = require(path.resolve('./config/lib/multer')).profileUploadFileFilter;

when I´m trying to upload a new image my server throws an error in the var upload = multer(); Line ...

> TypeError: undefined is not a function
        at exports.changeProfilePicture (/modules/locationCategories/server/controllers/locationCategories.server.controller.js:38:63)
        at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
        at next (/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
        at /node_modules/express/lib/router/index.js:277:22
        at param (/node_modules/express/lib/router/index.js:349:14)
        at paramCallback (/node_modules/express/lib/router/index.js:401:21)
        at /modules/locationCategories/server/controllers/locationCategories.server.controller.js:155:5
        at Query.<anonymous> (/node_modules/mongoose/lib/query.js:2119:28)
        at /node_modules/mongoose/node_modules/kareem/index.js:177:19
        at /node_modules/mongoose/node_modules/kareem/index.js:109:16
        at process._tickCallback (node.js:355:11)

Is there already an open issue and i can´t find it?! Or what am I doing wrong?

**Comment by lirantal** [comment]
@mleanos @gustavodemari can you look into it?

**Comment by gustavodemari** [comment]
@Meistercoach03 have you installed multer?

**Comment by Meistercoach83** [comment]
there was the problem - I had the old multer version installed.. i apologize for wasting your time

**Comment by gustavodemari** [comment]
@Meistercoach83 no problem. :)
@lirantal solved

**Comment by lirantal** [comment]
Great work @gustavodemari ! :laughing: 
Glad everything is ok now @Meistercoach83
