### ISSUE TITLE
npm ERR! network connect ETIMEDOUT 23.235.40.162:443

### ISSUE THREAD

**Issue by lamiastella** [meanjs/mean#1268]
Someone help me please! Not sure what's going wrong!
```
yosay@1.1.0 node_modules/generator-meanjs/node_modules/yo/node_modules/yosay -> node_modules/generator-meanjs/node_modules/yosay
/Users/mona/.nvm/versions/node/v4.0.0/lib
└─┬ generator-meanjs@0.4.4 
  ├─┬ yeoman-generator@0.21.1
  │ ├─┬ download@4.4.3
  │ │ ├─┬ gulp-decompress@1.2.0
  │ │ │ └─┬ decompress@3.0.0
  │ │ │   ├─┬ buffer-to-vinyl@1.1.0
  │ │ │   │ └─┬ readable-stream@2.0.6 
  │ │ │   │   └── isarray@1.0.0 
  │ │ │   ├─┬ decompress-tar@3.1.0
  │ │ │   │ └─┬ tar-stream@1.3.2
  │ │ │   │   ├─┬ bl@1.1.2
  │ │ │   │   │ └─┬ readable-stream@2.0.6 
  │ │ │   │   │   └── isarray@1.0.0 
  │ │ │   │   └─┬ readable-stream@2.0.6 
  │ │ │   │     └── isarray@1.0.0 
  │ │ │   └─┬ vinyl-assign@1.2.1
  │ │ │     └─┬ readable-stream@2.0.6 
  │ │ │       └── isarray@1.0.0 
  │ │ └─┬ vinyl-fs@2.4.2
  │ │   ├─┬ duplexify@3.4.3
  │ │   │ └─┬ readable-stream@2.0.6 
  │ │   │   └── isarray@1.0.0 
  │ │   ├─┬ glob-stream@5.3.2
  │ │   │ ├── glob@5.0.15 
  │ │   │ └─┬ ordered-read-streams@0.3.0
  │ │   │   └─┬ readable-stream@2.0.6 
  │ │   │     └── isarray@1.0.0 
  │ │   ├─┬ lazystream@1.0.0
  │ │   │ └─┬ readable-stream@2.0.6 
  │ │   │   └── isarray@1.0.0 
  │ │   └─┬ merge-stream@1.0.0
  │ │     └─┬ readable-stream@2.0.6 
  │ │       └── isarray@1.0.0 
  │ ├─┬ gruntfile-editor@1.1.0
  │ │ ├─┬ ast-query@1.1.0
  │ │ │ └── lodash@3.10.1 
  │ │ └── lodash@3.10.1 
  │ ├─┬ inquirer@0.11.4
  │ │ └── lodash@3.10.1 
  │ ├─┬ yeoman-assert@2.1.1
  │ │ └── lodash@3.10.1 
  │ └─┬ yeoman-environment@1.5.2
  │   ├─┬ grouped-queue@0.3.2
  │   │ └── lodash@3.10.1 
  │   └── lodash@3.10.1 
  └─┬ yo@1.5.1
    └─┬ insight@0.7.0
      ├─┬ inquirer@0.10.1
      │ └── lodash@3.10.1 
      └─┬ request@2.69.0
        └─┬ bl@1.0.3
          └─┬ readable-stream@2.0.6 
            └── isarray@1.0.0 

bash-3.2$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed later. mean
Cloning the MEAN repo.......
Error: Command failed: /bin/sh -c git clone --branch v0.4.0 https://github.com/meanjs/mean.git mean
fatal: destination path 'mean' already exists and is not an empty directory.

bash-3.2$ ls
app			bower_components	index.html		package.json		todomvc
bower.json		gulpfile.babel.js	mean			test
bash-3.2$ rm -rf mean/
bash-3.2$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed later. mean
Cloning the MEAN repo.......
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name? 
? Would you like to generate the article example CRUD module? Yes
? Would you like to generate the chat example module? Yes
Running npm install for you....
This may take a couple minutes.
Error: Command failed: /bin/sh -c cd mean && npm install
npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/mona/.nvm/versions/node/v4.0.0/bin/node" "/Users/mona/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v3.8.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 23.235.40.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mona/interviews/mean/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
bash-3.2$ 

```

**Comment by ilanbiala** [comment]
Any generator issues should be posted on the generator repo.

**Comment by Shailarun** [comment]
did you get the answer to the above problem. If yes then please do share.
