### ISSUE TITLE
socket.io was missing

### ISSUE THREAD

**Issue by flik** [meanjs/mean#1288]
package was not in the dependencies list.

**Comment by simison** [comment]
Hmm? https://github.com/meanjs/mean/blob/master/package.json#L65

**Comment by lirantal** [comment]
@flik ?

**Comment by flik** [comment]
@lirantal 
When you install with npm, You will face an error because of socket.io It is not included in dependencies list and MEAN is using it.

**Comment by simison** [comment]
@flik which version you're running?

At least it's here at the latest tagged version: https://github.com/meanjs/mean/blob/e14088039748ba515e7de3f5a44ec20965337537/package.json#L63

...and at master as I pointed out earlier.

**Comment by flik** [comment]
0.11.1

and I am getting these messages.  

/home/ashfaq/myA# gulp

Error: Cannot find module 'socket.io'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/ashfaq/myA/node_modules/karma/lib/server.js:1:78)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/ashfaq/myA/node_modules/karma/lib/index.js:4:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/ashfaq/myA/gulp/test.js:6:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at requireDir (/home/ashfaq/myA/node_modules/require-dir/index.js:116:33)
  at Object.<anonymous> (/home/ashfaq/myA/gulpfile.js:12:23)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3                )
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/                index.js:193:16)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_                modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/                index.js:185:9)
  at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:36:12
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:47:7
  at process._tickCallback (node.js:415:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by lirantal** [comment]
@flik 
What is 0.11.1?
I don't even remember such version :)

**Comment by flik** [comment]
root@ubuntu-512mb:~# mean -v
0.11.1
It is showing mean version

**Comment by lirantal** [comment]
@flik I don't know what project you are you using but MEAN.JS never had an 0.11.1 version.
Can you paste here your entire `package.json` file maybe?

**Comment by codydaig** [comment]
We don't have a mean command line interface. So running mean -v is not giving your the version of our project. Nor is using mean from the command line related to this project.

**Comment by Wuntenn** [comment]
sounds like mean.io
