### ISSUE TITLE
0.5.0 Boiler plater throwing server error

### ISSUE THREAD

**Issue by aquadestructor** [meanjs/mean#1326]
I tried cloning the beta version 0.5.0. However it's throwing a server error. The initial issue was in validator **TypeError: This library (validator.js) validates strings only**. I managed to fix it by adding the + ' ' in the assertString. It's still displaying the server error.

**Comment by aquadestructor** [comment]
Still showing the same error in the validator.js

**Comment by ilanbiala** [comment]
@aquadestructor where is this exactly?

**Comment by umairwanclouds** [comment]
@ilanbiala `TypeError: This library (validator.js) validates strings only
    at assertString (/Users/C_v/Documents/workplace/Personal/blog/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.escape (/Users/C_v/Documents/workplace/Personal/blog/node_modules/validator/lib/escape.js:15:34)
    at exports.renderIndex (/Users/C_v/Documents/workplace/Personal/blog/modules/core/server/controllers/core.server.controller.js:15:27)
    at Layer.handle [as handle_request] (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/layer.js:95:5)
    at /Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/index.js:277:22
    at param (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/C_v/Documents/workplace/Personal/blog/node_modules/express/lib/router/index.js:271:10)
    at SessionStrategy.strategy.pass (/Users/C_v/Documents/workplace/Personal/blog/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at /Users/C_v/Documents/workplace/Personal/blog/node_modules/passport/lib/strategies/session.js:65:12
    at pass (/Users/C_v/Documents/workplace/Personal/blog/node_modules/passport/lib/authenticator.js:327:31)
    at deserialized (/Users/C_v/Documents/workplace/Personal/blog/node_modules/passport/lib/authenticator.js:339:7)
    at Query.<anonymous> (/Users/C_v/Documents/workplace/Personal/blog/modules/users/server/config/users.server.config.js:25:7)
    at /Users/C_v/Documents/workplace/Personal/blog/node_modules/kareem/index.js:177:19
    at /Users/C_v/Documents/workplace/Personal/blog/node_modules/kareem/index.js:109:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
info: GET /lib/angular/angular.js 304 10.355 ms - -`
That's the error. That was a month ago. I moved back to 0.4.2. I tried using 0.5.0 again a few days back and its still the same.

**Comment by shanavas786** [comment]
@aquadestructor It seems the req.user.username is not a string.
Could you please check the value of `req.user` object or `req.user.username` at modules/core/server/controllers/core.server.controller.js line 11.

```
  if (req.user) {
    console.log(req.user);
....
```

**Comment by ilanbiala** [comment]
@aquadestructor did @shanavas786 comment help?

**Comment by mleanos** [comment]
@aquadestructor Does the version of MEANJS that you're using check for the existence of `req.user`, just as the *master* branch has?

https://github.com/meanjs/mean/blob/master/modules/core/server/controllers/core.server.controller.js#L11-L23

**Comment by lirantal** [comment]
@aquadestructor if the issue persists you're welcome to re-open for discussion and help.
