### ISSUE TITLE
mean.js installed using generator. but cannot call sudo npm install

### ISSUE THREAD

**Issue by zoonoo** [meanjs/mean#1350]
I was going through the tutorial [here](http://www.bradoncode.com/tutorials/mean-stack-tutorial-part-1-setup/)

Using Mac OS X El Capitan (V 10.11.4)
npm WARN lifecycle v8-profiler@5.2.12~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.2.12   /Users/zoonoo/dramaMean/node_modules/.staging/v8-profiler-10be8171
npm WARN prefer global node-inspector@0.9.2 should be installed with -g

> v8-profiler@5.2.12 install /Users/zoonoo/dramaMean/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.2.12/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.2.12 and node@6.1.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/profiler/src/profiler.o
In file included from ../src/profiler.cc:2:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64"
gyp ERR! cwd /Users/zoonoo/dramaMean/node_modules/v8-profiler
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zoonoo/dramaMean/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/Users/zoonoo/dramaMean/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zoonoo/dramaMean/node_modules/v8-profiler
node-pre-gyp ERR! node -v v6.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/zoonoo/dramaMean/node_modules/v8-profiler/build/profiler/v5.2.12/node-v48-darwin-x64' (1)
dramamean@0.0.1 /Users/zoonoo/dramaMean
+-- UNMET PEER DEPENDENCY grunt@1.0.1
| `-- UNMET PEER DEPENDENCY grunt@~0.4.0
`-- UNMET PEER DEPENDENCY mocha@>=1.20.0

npm WARN grunt-contrib-nodeunit@0.4.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-csslint@0.3.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-cssmin@0.10.0 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-contrib-jshint@0.10.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-uglify@0.6.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-watch@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-mocha-test@0.12.7 requires a peer of mocha@>=1.20.0 but none was installed.
npm WARN grunt-ng-annotate@0.4.0 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-nodemon@0.3.0 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-node-inspector@0.1.6 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN dramamean@0.0.1 No repository field.
npm WARN dramamean@0.0.1 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.2.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.2.12 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zoonoo/dramaMean/npm-debug.log
npm ERR! code 1

**Comment by zoonoo** [comment]
![screen shot 2016-05-28 at 1 26 09 pm](https://cloud.githubusercontent.com/assets/5508584/15625186/f17db538-24d7-11e6-8e38-e4d72129f211.png)
![screen shot 2016-05-28 at 1 26 28 pm](https://cloud.githubusercontent.com/assets/5508584/15625187/f25b8192-24d7-11e6-81f5-0132b037ecd6.png)

**Comment by Ripley511** [comment]
I ran in a similar problem, with node v4.4.5
Switched to node v0.12@latest, now it's working (using nvm).

I gathered on other threads that some dependencies were not updated to use node > 0.12, probably node-gyp and node-pre-gyp are part of these dependencies.

**Comment by lirantal** [comment]
@zoonoo seems to be build issues related to your OS/environment.
Hope you got it sorted out by now.
