### ISSUE TITLE
Error: EACCES: permission denied in yo

### ISSUE THREAD

**Issue by amedice** [meanjs/mean#1442]
root@fdd55a49772b:/opt/mean.js# yo
/usr/lib/node_modules/yo/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by hyperreality** [comment]
Try running Yeoman as an ordinary user rather than root.

**Comment by lirantal** [comment]
@amedice you'll get better responses also when asking in the generator repository: https://github.com/meanjs/generator-meanjs
