### ISSUE TITLE
cannot find module bl

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1514]
```
 Error: Cannot find module 'bl'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/opt/node_modules/request/request.js:9:10)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/opt/node_modules/request/index.js:145:19)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/opt/node_modules/pusher/lib/requests.js:1:77)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/opt/node_modules/pusher/lib/pusher.js:6:16)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
    /opt/mean/node_modules/mongoose/node_modules/mongodb/lib/server.js:309
          process.nextTick(function() { throw err; })
                                        ^

```

any reason? im getting that no matter what :P

**Comment by lirantal** [comment]
That doesn't make a lot of sense.
Does it still happen? can you share more background?

**Comment by Ilon4ik** [comment]
Where you able to resolve this?
