### ISSUE TITLE
npm install failed for node-inspector

### ISSUE THREAD

**Issue by luebken** [meanjs/mean#1675]
````

npm install

> v8-debug@0.7.7 preinstall /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/.staging/v8-debug-c61c377d
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2, have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/mdl/.node-gyp/7.2.0/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument 'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mdl/.node-gyp/7.2.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mdl/.node-gyp/7.2.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument 'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mdl/.node-gyp/7.2.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext' declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/7.2.0/bin/node" "/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64"
gyp ERR! cwd /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.2.0/bin/node /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.2.0/bin/node" "/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.2.0/bin/node /Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64/debug.node --module_name=debug --module_path=/Users/mdl/workspace/redhat/examples/meanjs-app/node_modules/v8-debug/build/debug/v0.7.7/node-v51-darwin-x64' (1)
meanjs@0.5.0 /Users/mdl/workspace/redhat/examples/meanjs-app
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mdl/workspace/redhat/examples/meanjs-app/npm-debug.log
npm ERR! code 1

````

**Comment by luebken** [comment]
Current workaround:  remove  "node-inspector": "~0.12.8",

**Comment by simison** [comment]
The project doesn't support Node v7 yet — #1652 #1657 #1655

**Comment by simison** [comment]
@luebken any other issues while running the app on Node v7? Would be glad to hear.

**Comment by luebken** [comment]
I see many issues but I'm unsure which are related to v7.

**Comment by luebken** [comment]
@simison 
These are the steps I needed to do:
* remove "node-inspector": "~0.12.8" from package.json
* get the right versions for https://github.com/meanjs/mean/issues/1674
* do something for node-sass: https://github.com/meanjs/mean/issues/1676

when running `npm start` I'm seeing a couple of errors like `no-useless-escape`, `global-require` from a couple of js files. but it brought up mean. so I'm not investigating those.

**Comment by kybarg** [comment]
Having same problem on `node 6.9.4`

**Comment by lirantal** [comment]
Thanks @luebken @kybarg 
FYI https://github.com/meanjs/mean/pull/1744 fixes the issue now, merged to master already.
