### ISSUE TITLE
npm run fails node-sass

### ISSUE THREAD

**Issue by luebken** [meanjs/mean#1676]
``` 
npm start

> meanjs@0.5.0 start /Users/mdl/workspace/redhat/examples/meanjs-app2
> gulp

[14:12:41] Using gulpfile ~/workspace/redhat/examples/meanjs-app2/gulpfile.js
[14:12:41] Starting 'default'...
[14:12:41] Starting 'env:dev'...
[14:12:41] Finished 'env:dev' after 88 μs
[14:12:41] Starting 'copyLocalEnvConfig'...
[14:12:41] Starting 'makeUploadsDir'...
[14:12:41] Finished 'makeUploadsDir' after 66 μs
[14:12:41] Finished 'copyLocalEnvConfig' after 22 ms
[14:12:41] Starting 'lint'...
[14:12:41] Starting 'less'...
[14:12:41] Finished 'less' after 396 ms
[14:12:41] Starting 'sass'...
[14:12:41] 'sass' errored after 9.96 ms
[14:12:41] Error: ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.getInstalledBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:571:32)
[14:12:41] 'default' errored after 431 ms
[14:12:41] Error in plugin 'run-sequence(sass)'
Message:
    ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.getInstalledBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:571:32)
[14:12:41] 'lint' errored after 408 ms
[14:12:41] Error in plugin 'run-sequence(default)'
Message:
    ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.getInstalledBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:571:32)
[14:12:41] 'lint' errored after 409 ms
[14:12:41] Error in plugin 'run-sequence(sass)'
Message:
    ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.getInstalledBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mdl/workspace/redhat/examples/meanjs-app2/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! meanjs@0.5.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanjs@0.5.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meanjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meanjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meanjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mdl/workspace/redhat/examples/meanjs-app2/npm-debug.log

```

**Comment by luebken** [comment]
I think I fixed it with `nodejs node_modules/node-sass/scripts/install.js` found here: https://github.com/sass/node-sass/issues/1579#issuecomment-227661284

**Comment by kybarg** [comment]
`node rebuild node-sass`

**Comment by akansharaut** [comment]
I have also found same issue but its resolved using npm rebuild node-sass?
but what does "npm rebuild node-sass" exactly do?

**Comment by Wuntenn** [comment]
@akansharaut Some binaries need to be (re-)compiled to target the version of Node that you're using.

If your version of Node is inconsistent with the version of `node-sass` for example, then running: `npm rebuild node-sass` will recompile the associated binaries: https://docs.npmjs.com/cli/rebuild

**Comment by lirantal** [comment]
Closing as non-issue.
