### ISSUE TITLE
npm install bugs out at graceful-fs@^4.0.0

### ISSUE THREAD

**Issue by JamesDaniel** [meanjs/mean#1681]
Hello, I'm having trouble starting my clone of meanjs. I followed the instructions from README.md . The only things extra that i needed to install was gulp globally. I only got this far after that. I can install packages individually but when I try `npm install` it bugs out.
```
user@ubuntu-16:~/nodejs_apps/mean$ npm start

> meanjs@0.5.0 start /home/user/nodejs_apps/mean
> gulp

module.js:472
    throw err;
    ^

Error: Cannot find module 'imagemin-pngquant'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/nodejs_apps/mean/gulpfile.js:20:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! meanjs@0.5.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanjs@0.5.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meanjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meanjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meanjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/nodejs_apps/mean/npm-debug.log
user@ubuntu-16:~/nodejs_apps/mean$ npm install
npm WARN deprecated mongodb@2.2.11: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return             value
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update             to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed ............] / fetchMetadata: verb afterAdd /home/user/.npm/svgo/0.7.1/package/package.json written
```

My system is Ubuntu 16.04.1x64.
I installed bower globally. I then tried installing with the command `npm install` but it failed because I didn't have gulp installed globally. I installed gulp and tried again but got similar output as shown above. I updated nodejs as suggested `Make sure you have the latest version of node.js and npm installed.`. I tried `npm install` again but got the output shown above.

<hr />
I tride now with `sudo npm install` and am getting different output.

```
user@ubuntu-16:~/nodejs_apps/mean$ sudo npm install
npm WARN deprecated mongodb@2.2.11: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return value
Killed ............] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/should
```

**Comment by hyperreality** [comment]
Node 7 isn't supported yet, please try with node 6

**Comment by TylerL-uxai** [comment]
Downgraded to node 6 using homebrew

```
$ npm test --force
npm WARN using --force I sure hope you know what you are doing.

> myApp@0.4.2 test /Users/tdiddy/meaning42
> grunt test

Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
Warning: Task "karma:unit" not found. Use --force to continue.

Aborted due to warnings.

```

**Comment by lirantal** [comment]
@JamesDaniel  mean.js is compatible with node v7 and our travis build matrix isn't reproducing any failed npm installs. You're welcome to re-open issue if you can share more info on this.
