### ISSUE TITLE
MEAN.js does not compatible with latest Node

### ISSUE THREAD

**Issue by w1ndy** [meanjs/mean#1719]
Pulling from master branch today and running ``npm i`` result in:
```
npm WARN deprecated mongodb@2.2.11: Please upgrade to 2.2.19 or higher
npm WARN deprecated ignore@2.2.19: several bugs fixed in v3.2.1
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> v8-debug@0.7.7 preinstall /home/charles/proj/node_modules/.staging/v8-debug-cd3c832e
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /home/charles/proj/node_modules/.staging/v8-profiler-58554b65
> node -e 'process.exit(0)'

npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> v8-debug@0.7.7 install /home/charles/proj/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.5.0 (node-v51 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/charles/proj/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/charles/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
debug.target.mk:97: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/charles/proj/node_modules/v8-debug/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/charles/proj/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/home/charles/proj/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/charles/proj/node_modules/v8-debug
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/charles/proj/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/charles/proj/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-59-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/charles/proj/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/charles/proj/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /home/charles/proj/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/charles/proj/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
meanjs@0.5.0 /home/charles/proj
...
```

**Comment by prateekvarma** [comment]
i get a very similar error

**Comment by ikhsanalatsary** [comment]
i just to use node v6 LTS version

**Comment by w1ndy** [comment]
Package node-inspector is broken on Node 7.0+. I would suggest use Node internal debugger (activated by --inspect flag, available since 6.3.0) instead of node-inspector. Also noticed several out-dated dependencies needed to be updated accordingly.

**Comment by lirantal** [comment]
as @w1ndy said, and I've got a PR I'll push tomorrow to deprecate node-inspector infavor of the builtin debugger functionality in Node.js. Hang tight.

**Comment by lirantal** [comment]
FYI @w1ndy https://github.com/meanjs/mean/pull/1744 fixes the problem now, already merged to master.

**Comment by w1ndy** [comment]
@lirantal Good job, thanks!

**Comment by prateekvarma** [comment]
@lirantal Thanks man!

**Comment by lirantal** [comment]
my pleasure guys, thanks for reporting back 👍
