### ISSUE TITLE
meanjs 0.4.0 not working when deployed to Heroku

### ISSUE THREAD

**Issue by armedirken** [meanjs/mean#1788]
I've just tried the meanjs 0.4.0 in local host and runs fine but when I deploy to heroku [(link to app here)](https://meanjsapptest.herokuapp.com/authentication/signup) and try the "Sign up" option I get this in the navegator console: 

> POST https://meanjsapptest.herokuapp.com/api/auth/signup 503 (Service Unavailable)

and when I write the comand `heroku logs` in the CLI I get:
> 2017-06-06T04:15:35.152983+00:00 app[web.1]: (node:16) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2017-06-06T04:15:35.153005+00:00 app[web.1]: crypto.js:635
2017-06-06T04:15:35.153006+00:00 app[web.1]:     throw new TypeError(
2017-06-06T04:15:35.153006+00:00 app[web.1]:     ^
2017-06-06T04:15:35.153007+00:00 app[web.1]:
2017-06-06T04:15:35.153008+00:00 app[web.1]: TypeError: The "digest" argument is required and must not be undefined
2017-06-06T04:15:35.153009+00:00 app[web.1]:     at pbkdf2 (crypto.js:635:11)
2017-06-06T04:15:35.153010+00:00 app[web.1]:     at Object.exports.pbkdf2Sync (crypto.js:628:10)
2017-06-06T04:15:35.153012+00:00 app[web.1]:     at model.<anonymous> (/app/modules/users/server/models/user.server.model.js:112:26)
2017-06-06T04:15:35.153011+00:00 app[web.1]:     at model.UserSchema.methods.hashPassword (/app/modules/users/server/models/user.server.model.js:123:19)
2017-06-06T04:15:35.153013+00:00 app[web.1]:     at _next (/app/node_modules/hooks-fixed/hooks.js:62:30)
2017-06-06T04:15:35.153013+00:00 app[web.1]:     at fnWrapper (/app/node_modules/hooks-fixed/hooks.js:186:8)
2017-06-06T04:15:35.153014+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/plugins/saveSubdocs.js:20:7)
2017-06-06T04:15:35.153014+00:00 app[web.1]:     at _next (/app/node_modules/hooks-fixed/hooks.js:62:30)
2017-06-06T04:15:35.153015+00:00 app[web.1]:     at fnWrapper (/app/node_modules/hooks-fixed/hooks.js:186:8)
2017-06-06T04:15:35.153015+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/plugins/validateBeforeSave.js:33:13
2017-06-06T04:15:35.153016+00:00 app[web.1]:     at /app/node_modules/kareem/index.js:131:16
2017-06-06T04:15:35.153016+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:95:7)
2017-06-06T04:15:35.153017+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:161:9)
2017-06-06T04:15:35.167579+00:00 app[web.1]: error: Forever detected script exited with code: 1
2017-06-06T04:15:35.173500+00:00 app[web.1]: error: Script restart attempt #1
2017-06-06T04:15:35.292903+00:00 app[web.1]:
2017-06-06T04:15:35.294191+00:00 app[web.1]:
2017-06-06T04:15:35.310954+00:00 app[web.1]: + Error: Certificate file or key file is missing, falling back to non-SSL mode
2017-06-06T04:15:35.311037+00:00 app[web.1]:   To create them, simply run the following from your shell: sh ./scripts/generate-ssl-certs.sh
2017-06-06T04:15:35.311039+00:00 app[web.1]:
2017-06-06T04:15:35.916892+00:00 app[web.1]: Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

I don't know what to do now because Heroku supports tell me thar the error is in my code but I haven't changed anything there!

![captura](https://cloud.githubusercontent.com/assets/22604301/26813710/9b78fb0e-4a45-11e7-955e-a24356e85252.PNG)

![captura 1](https://cloud.githubusercontent.com/assets/22604301/26813731/c589d1e8-4a45-11e7-9b7c-ad04b36eccf7.PNG)

**Comment by armedirken** [comment]
I had to change the node version in Package.js from ">=0.10.0" to "6.6.0" and now it's working fine.

**Comment by lirantal** [comment]
I'll update our engines to reflect 6.10, but where did you get that 0.4.0 version to begin with? this is the generator? because 0.10.0 seems rather an old entry

**Comment by armedirken** [comment]
Yes. The package.js show a node version "node": ">=0.10.0" when I used the Yeoman generator.
