### ISSUE TITLE
Upgrade Mongoose to 4.11

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1814]
Just wanted to give heads up:

Mongoose 4.11 has quite some changes which affect Mean.js and upgrading requires some changes to the codebase.

It could be a good change to update to [new mongoose connection logic](http://mongoosejs.com/docs/connections.html#use-mongo-client):
>Mongoose's default connection logic is deprecated as of 4.11.0. Please opt in to the new connection logic using the `useMongoClient` option, but make sure you test your connections first if you're upgrading an existing codebase!

For instance `connect-mongo` [now accepts promises](https://github.com/jdesboeufs/connect-mongo#re-use-a-native-mongodb-driver-connection-or-a-promise) as well.

I probably won't be able to make a PR any time soon though...

**Comment by simison** [comment]
I'm also getting these errors when running tests when attempting upgrade:
```
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (/mean/node_modules/mongoose/lib/index.js:395:13)
    at Object.<anonymous> (/mean/modules/core/tests/server/core.server.config.tests.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /mean/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mean/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/mean/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/mean/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I upgraded also Mocha so this might be coming from there as well.

**Comment by lirantal** [comment]
Thanks for the heads up!

**Comment by simison** [comment]
Opened a PR with some work on this, _might_ continue working on it, but that might be next week or next month or in 3 months... :-)

**Comment by lirantal** [comment]
Cool. Hopefully it's not a lot of work too.

**Comment by mleanos** [comment]
I'll start work on this, and use the referenced PR as a guide. Thanks Mikael!
