### ISSUE TITLE
Test watching broken

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1840]
Run:
```
npm run test:server:watch
```

Tests pass just fine. Modify a file and task will fail with:
```
error: uncaughtException: Path must be a string. Received undefined date=Fri Aug 11 2017 11:39:20 GMT+0300 (EEST), pid=5690, uid=501, gid=20, cwd=/Users/mikael/Documents/Projects/TrustRoots/mean, execPath=/usr/local/bin/node, version=v6.9.5, argv=[/usr/local/bin/node, /mean/node_modules/.bin/gulp, test:server:watch], rss=118480896, heapTotal=106631168, heapUsed=84892280, loadavg=[3.04443359375, 2.39013671875, 2.18408203125], uptime=1201347
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Function.exports.changed (/mean/node_modules/gulp-refresh/index.js:129:33)
    at EventEmitter.<anonymous> (/mean/gulpfile.js:116:21)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Gaze.<anonymous> (/mean/node_modules/glob-watcher/index.js:17:11)
    at emitTwo (events.js:106:13)
    at Gaze.emit (events.js:191:7)
    at Gaze.emit (/mean/node_modules/gaze/lib/gaze.js:129:32)
    at /mean/node_modules/gaze/lib/gaze.js:415:16
    at StatWatcher._pollers.(anonymous function) (/mean/node_modules/gaze/lib/gaze.js:326:7)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1487:10)
```

**Comment by gbatz** [comment]
Hi, I fixed this problem in my project. Will do a PR here, hopefully tomorrow

**Comment by simison** [comment]
@gbatz You're the best!! <3

**Comment by gbatz** [comment]
Basically an exception was thrown by the `path` module, because it was being invoked by gulp-refresh plugin with no parameter, line 116: `plugins.refresh.changed()`
