### ISSUE TITLE
User CRUD tests "before all" hook

### ISSUE THREAD

**Issue by amitsin6h** [meanjs/mean#1948]
Hello all am using Node Version: 6.12.2
When am tried to run `grunt test ` it didn't run.
As I was required to update the mock-fs version to 3.12.1("mock-fs": "~3.12.1").

After updating I tried to run `grunt test` I got  error:
```
User CRUD tests "before all" hook:
     TypeError: Cannot read property 'isDirectory' of undefined
      at resolveSync (/home/amitsin6h/meanjs/MeanjsApp/node_modules/serve-favicon/index.js:174:11)
      at favicon (/home/amitsin6h/meanjs/MeanjsApp/node_modules/serve-favicon/index.js:61:12)
      at Object.module.exports.initMiddleware (/home/amitsin6h/meanjs/MeanjsApp/config/lib/express.js:68:11)
      at Object.module.exports.init (/home/amitsin6h/meanjs/MeanjsApp/config/lib/express.js:227:8)
      at Context.<anonymous> (/home/amitsin6h/meanjs/MeanjsApp/modules/users/tests/server/user.server.routes.tests.js:30:19)
      at Hook.Runnable.run (/home/amitsin6h/meanjs/MeanjsApp/node_modules/mocha/lib/runnable.js:196:15)
      at next (/home/amitsin6h/meanjs/MeanjsApp/node_modules/mocha/lib/runner.js:258:10)
      at Immediate.<anonymous> (/home/amitsin6h/meanjs/MeanjsApp/node_modules/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)

```

![screenshot from 2018-02-26 00-38-19](https://user-images.githubusercontent.com/12906090/36645359-6616dca6-1a8d-11e8-8a1a-95f732fe4087.png)

**Comment by s0j0hn** [comment]
Why not use node LTS or Latest version ?
