### ISSUE TITLE
Can't Create MeanJS - Build failed

### ISSUE THREAD

**Issue by tbhaxor** [meanjs/mean#1980]
node version : v10.5.0
npm version : 6.1.0
yo version : 2.0.3
generator-meanjs version : 0.4.5

Error: some g++ build warning and 2 NPM error
_$ npm install_
```bash
make: Leaving directory '/mnt/LEARNSS/mean-stack-for-web-developers/codesnippets/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/LEARNSS/mean-stack-for-web-developers/codesnippets/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.17.2-1-ARCH
gyp ERR! command "/usr/bin/node" "/mnt/LEARNSS/mean-stack-for-web-developers/codesnippets/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /mnt/LEARNSS/mean-stack-for-web-developers/codesnippets/node_modules/node-sass
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/terabyte/.npm/_logs/2018-07-03T04_36_26_473Z-debug.log

```

**Comment by JagathesanNB** [comment]
same problem for me also.

**Comment by Root-Control** [comment]
npm rebuild node-sass

**Comment by tbhaxor** [comment]
@Root-Control still it is not installing

**Comment by Root-Control** [comment]
What are your current nodejs version?

**Comment by Root-Control** [comment]
1.- Make sure you are using the latest lts version (no latest with all features)
2.- don't use yeoman, its failing with meanjs scaffolding
3.- Download the last meanjs version in github repository
4.- Run again npm install

**Comment by tbhaxor** [comment]
10.6.0

**Comment by eliavmaman** [comment]
Build failed even when download the repo (not yoman)... same error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by Root-Control** [comment]
it working fine on my computer.
Node version 8.9.4
npm version 6.1.0
Please try aplying before "npm cache clean --force"
Then if still failing try to download dependencies with yarn

**Comment by tbhaxor** [comment]
well i figured out, i read it somewhere and they said that MEAN-JS is not compatible with node 10x because it depends on node-sass and node-sass is not compatible with node 10x atleast in Arch Linux
