### ISSUE TITLE
"npm install" on macOS mojave

### ISSUE THREAD

**Issue by magpielover** [meanjs/mean#2009]
Hello,
Freshly cloned the repository, first command hit. The error code is as follows:
Any idea what's the problem?
Cheers

`npm install`

> node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.6.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@11.6.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
> 7 warnings and 1 error generated.
> 7 warnings and 1 error generated.
> make: *** [Release/obj.target/fse/fsevents.o] Error 1
> make: *** [Release/obj.target/fse/fsevents.o] Error 1
> gyp ERR! gypbuild error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Darwin 18.2.0
> gyp ERR! ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Darwin 18.2.0
>  command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ugur/Desktop/Server_Docker/mean/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ugur/Desktop/Server_Docker/mean/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64"
> gyp ERR! cwdgyp /Users/ugur/Desktop/Server_Docker/mean/node_modules/fsevents

**Comment by ilanbiala** [comment]
Can you try now with master?
