### ISSUE TITLE
Getting errors on npm install and npm start on Windows

### ISSUE THREAD

**Issue by AnnaShalaginova** [meanjs/mean#2040]
Please see the npm install and npm start warnings and errors below.

npm install
`> meanjs@0.5.0 start myfilepath\meanjs
> gulp

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\ASHALAGI\meanjs\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\ASHALAGI\meanjs\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\ASHALAGI\meanjs\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meanjs@0.5.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanjs@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASHALAGI\AppData\Roaming\npm-cache\_logs\2020-03-05T19_14_37_278Z-debug.log
`
npm start
`
> meanjs@0.5.0 postinstall myfilepath\meanjs
> npm run bower

> meanjs@0.5.0 bower myfilepath\meanjs
> bower install --allow-root && bower prune --allow-root

npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 21524 packages in 9.26s

4 packages are looking for funding
  run `npm fund` for details

found 185 vulnerabilities (79 low, 39 moderate, 65 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\ASHALAGI\meanjs>npm start

> meanjs@0.5.0 start C:\Users\ASHALAGI\meanjs
> gulp

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\ASHALAGI\meanjs\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\ASHALAGI\meanjs\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\ASHALAGI\meanjs\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meanjs@0.5.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanjs@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASHALAGI\AppData\Roaming\npm-cache\_logs\2020-03-05T19_42_02_180Z-debug.log

`

**Comment by AnnaShalaginova** [comment]
As a result, the app is not opening on http://localhost:3000/

**Comment by dalelotts** [comment]
Hey Anna, it's pretty safe to say this project is no longer maintained. It's been years since the last commit.

Can anyone recommend another starter project for Anna?

**Comment by AnnaShalaginova** [comment]
Thank you! This repo was referenced in this tutorial: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-nodejs-mongodb-app

**Comment by dalelotts** [comment]
That's unfortunate.  Please consider a PR or new issue in https://github.com/MicrosoftDocs/azure-docs/ to update the docs with something current. Help out the people coming behind you. =)

**Comment by dalelotts** [comment]
@AnnaShalaginova consider closing this issue because this project is no longer maintained.
