### ISSUE TITLE
Error: Error setting TTL index on collection

### ISSUE THREAD

**Issue by stayko** [meanjs/mean#224]
Hi there,

When running 'grunt' after generating my Mean.JS project with Yoeman and visiting my localhost I get the following error:

```
 NODE_ENV is not defined! Using default development environment

MEAN.JS application started on port 3000

/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;      
              ^
Error: Error setting TTL index on collection : sessions
    at /Users/Stayko/work/meanjs/node_modules/connect-mongo/lib/connect-mongo.js:161:23
    at /Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1288:11
    at Server.Base._callHandler (/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:478:18
    at MongoReply.parseBody (/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/Stayko/work/meanjs/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
[nodemon] app crashed - waiting for file changes before starting...
```

I have my mongo db listening for connections in the other tab. I started it using the command 'mongod'. 

Thanks

**Comment by vko-online** [comment]
This issue is still open. 

server.js file
```
root@linux~/demo# vim server.js 

var init = require('./config/init')(),
        config = require('./config/config'),
        mongoose = require('mongoose'),
        chalk = require('chalk');

/**
 * Main application entry file.
 * Please note that the order of loading is important.
 */

// Bootstrap db connection
var db = mongoose.connect(config.db, function(err) {
        if (err) {
                console.error(chalk.red('Could not connect to MongoDB!'));
                console.log(chalk.red(err));
        } else {
                var app = require('./config/express')(db);
                require('./config/passport')();
                app.listen(config.port);
                exports = module.exports = app;
                console.log('App running on port', config.port);
        }
});

// Init the express application
//var app = require('./config/express')(db);

// Bootstrap passport config
//require('./config/passport')();

// Start the app by listening on <port>
//app.listen(config.port);

// Expose app

// Logging initialization
//console.log('MEAN.JS application started on port ' + config.port);
```

`grunt` still throws error
```bash
App running on port 4000
/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
Error: Error setting TTL index on collection : sessions
    at /root/demo/node_modules/connect-mongo/lib/connect-mongo.js:169:23
    at /root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1354:11
    at Server.Base._callHandler (/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/root/demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by lirantal** [comment]
@vko-online looks like you're using an old version of MEAN.JS
