### ISSUE TITLE
Amazon EC2 Deploy Problem

### ISSUE THREAD

**Issue by boris-petrov1214** [meanjs/mean#300]
Hi,

I recently build an app using MEAN.JS and deployed as a production mode on to Amazon EC2 Ubuntu instance. 

I used forever and upstart to keep the server running on reboot and here's forever command :
>>>
forever start /home/ubuntu/ESP-connector/server.js
>>>

But the problem is that this command doesn't work and I got error like below:
>>>
Potentially unhandled rejection [1] MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (/home/ubuntu/ESP-connector/node_modules/mongoose/lib/index.js:323:13)
    at Object.<anonymous> (/home/ubuntu/ESP-connector/config/passport.js:7:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/ubuntu/ESP-connector/server.js:37:5
    at tryCatchReject (/home/ubuntu/ESP-connector/node_modules/amqplib/node_modules/when/lib/makePromise.js:806:14)
>>>

I realized that the error comes from this part in config/express.js file:
>>>
        // Globbing model files
	config.getGlobbedFiles('./app/models/**/*.js').forEach(function(modelPath) {
		require(path.resolve(modelPath));
	});
>>>

Is there anyone who can help me to solve this problem?

**Comment by ilanbiala** [comment]
@boris-petrov1214 does your app connect to the database before the error?

**Comment by codydaig** [comment]
@boris-petrov1214 Is this still an issue or can it be closed?

**Comment by codydaig** [comment]
@ilanbiala Can this issue be closed?

@boris-petrov1214 If your still having issues, feel free to reopen.
