### ISSUE TITLE
Adding angular dependencies to mean 0.3

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#415]
I'm trying to port the upload functionality present in the mean 0.4 branch to mean 0.3 but am stuck with getting the angular bit in. I've added the dependency to bower.json, installed it using bower. After that I added the 'angularFileUpload' dependency to config.js -- applicationModuleVendorDependencies as follows : 

    var applicationModuleVendorDependencies = ['ngResource', 'ngCookies',  'ngAnimate',  'ngTouch',  'ngSanitize',  'ui.router', 'ui.bootstrap', 'ui.utils','angularFileUpload'];

After that I used it in the Settings controller as follows : 
   
    var app = angular.module('users').controller('SettingsController', ['$scope', '$http', '$location', 'Users', 'Authentication', '$timeout', '$window', 'FileUploader',
	function($scope, $http, $location, Users, Authentication, $timeout, $window, FileUploader) {

When I run the page, I get the following error on the page: 

<code>
Uncaught Error: [$injector:modulerr] Failed to instantiate module myproject due to:
Error: [$injector:modulerr] Failed to instantiate module angularFileUpload due to:
Error: [$injector:nomod] Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=angularFileUpload
    at http://localhost:3030/lib/angular/angular.js:78:12
    at http://localhost:3030/lib/angular/angular.js:1677:17
    at ensure (http://localhost:3030/lib/angular/angular.js:1601:38)
    at module (http://localhost:3030/lib/angular/angular.js:1675:14)
    at http://localhost:3030/lib/angular/angular.js:3877:22
    at forEach (http://localhost:3030/lib/angular/angular.js:325:18)
    at loadModules (http://localhost:3030/lib/angular/angular.js:3871:5)
    at http://localhost:3030/lib/angular/angular.js:3878:40
    at forEach (http://localhost:3030/lib/angular/angular.js:325:18)
    at loadModules (http://localhost:3030/lib/angular/angular.js:3871:5)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=angularFileUpload&…s%20(http%3A%2F%2Flocalhost%3A3030%2Flib%2Fangular%2Fangular.js%3A3871%3A5)
    at http://localhost:3030/lib/angular/angular.js:78:12
    at http://localhost:3030/lib/angular/angular.js:3905:15
    at forEach (http://localhost:3030/lib/angular/angular.js:325:18)
    at loadModules (http://localhost:3030/lib/angular/angular.js:3871:5)
    at http://localhost:3030/lib/angular/angular.js:3878:40
    at forEach (http://localhost:3030/lib/angular/angular.js:325:18)
    at loadModules (http://localhost:3030/lib/angular/angular.js:3871:5)
    at createInjector (http://localhost:3030/lib/angular/angular.js:3811:11)
    at doBootstrap (http://localhost:3030/lib/angular/angular.js:1444:20)
    at Object.bootstrap (http://localhost:3030/lib/angular/angular.js:1459:12)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=doctorportal&p1=Er…%20(http%3A%2F%2Flocalhost%3A3030%2Flib%2Fangular%2Fangular.js%3A1459%3A12) </code>

I have this issue whenever I try to add a new dependency to angular. Any help will be greatly appreciated. Thanks

**Comment by karan-kapoor90** [comment]
Solved by adding 

    'public/lib/angular-file-upload/angular-file-upload.min.js',

to config\env\all.js in the assets:[lib:[js:]] array
