### ISSUE TITLE
Resetting password error

### ISSUE THREAD

**Issue by maelvis** [meanjs/mean#556]
Hi,

Please I have a problem when implementing "password reset" functionnality.
Here is the error
```
Error: DEPTH_ZERO_SELF_SIGNED_CERT
    at SecurePair.<anonymous> (tls.js:1370:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at Socket.ondata (stream.js:51:26)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
```

Tow new fields has been added by updating the user : ```resetPasswordExpires``` and ```resetPasswordToken```.

What does the error mean please ?
How and where to configure the email using a gmail account as sender ? 
I just notice the presence of ```process.env.MAILER_*``` but I don't see where it has been configured.

Thanks.

**Comment by pgrodrigues** [comment]
You can configure the mailer in `config/env/` directory. According to your needs edit the development, production or test js files (mailer property).

**Comment by maelvis** [comment]
Thank you. I dit it and it's working.
