### ISSUE TITLE
Cannot Set Property Host of <IncomingMessage> which has only a getter | App  Crashes

### ISSUE THREAD

**Issue by afhaque** [meanjs/mean#597]
Hey guys,

I've got an initial application working having set things up via Yeoman. I'm able to add articles and list articles when using the initial template content. 

But after adding my own CRUD-module using the crud generator my app is crashing whenever I attempt to select any entry I create. 

In my case, for instance, I created "Hosts" list The below error occurs whenever I try to click on any item I select. 

> yo meanjs:crud-module hosts (This works. Hosts is added to the top menu.)

Once I add a menu item the app crashes with the error below. When I restart the app and click: "List Items" the item I added does in fact show up, but then again when I attempt to click any Host item, I once again get the error below. 

Sort of leaves me at a standstill... 

TypeError: Cannot set property host of #<IncomingMessage> which has only a getter
    at Promise.<anonymous> (F:\Code Projects\Iftar Project2\app\controllers\hosts.server.controller.js:94:12)
    at Promise.<anonymous> (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:97:20)
    at Promise.resolve (F:\Code Projects\Iftar Project2\node_modules\mongoose\lib\promise.js:114:23)
    at Promise.<anonymous> (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (F:\Code Projects\Iftar Project2\node_modules\mongoose\node_modules\mpromise\lib\promise.js:97:20)
[nodemon] app crashed - waiting for file changes before starting...

![image](https://cloud.githubusercontent.com/assets/5855843/8217917/ad2cb93e-1505-11e5-9c17-5b09053ae50f.png)

![image](https://cloud.githubusercontent.com/assets/5855843/8217923/b1ffae3a-1505-11e5-801e-f5d3028ea673.png)

After clicking a link:
![image](https://cloud.githubusercontent.com/assets/5855843/8217928/b659b41c-1505-11e5-8e78-b9f9b2b4da3f.png)

This is then followed by the error I showed earlier.

**Comment by isotnikov** [comment]
@afhaque show me your host mongoose model and hosts.server.controller.js:94

**Comment by codydaig** [comment]
@afhaque - Is this still an issue?

**Comment by codydaig** [comment]
@afhaque If this is still an issue, go ajead and reopen, otherwise @lirantal i think we can close this.
