### ISSUE TITLE
stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by AswathyRaju** [meanjs/mean#918]
Hi,

When I run 'yo meanjs' in ubuntu , getting 

Unhandled rejection Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:258:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)

why this happen? how to solve this issue?
Please

**Comment by simison** [comment]
generator isn't up to date with current version (0.4.x). There's probably some way to use it with older version (0.3.x), but I'd recommend to just skip using yo and simply clone the master branch.

**Comment by ilanbiala** [comment]
@simison yes it is. @AswathyRaju not the right repo. Please repost at generator-meanjs.

**Comment by simison** [comment]
@ilanbiala Ah, good to know! Cheers.
