### ISSUE TITLE
E2E Tests error out but don't fail the build

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#961]
```
[4mRunning "protractor:e2e" (protractor) task[24m
webdriver-manager path: /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip...
chromedriver_2.15.zip downloaded to /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver_2.15.zip
selenium-server-standalone-2.45.0.jar downloaded to /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://172.17.0.142:49446/wd/hub

/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-40-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.14 seconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'testing-worker-linux-docker-207121c9-3188-linux-3', ip: '172.17.0.142', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:158:24
    at [object Object].promise.ControlFlow.runInFrame_ (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at goog.async.run.processWorkQueue (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:180:37)
    at /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:256:21
    at _fulfilled (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/travis/build/meanjs/mean/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1
[31m>> [39m
[32m>> [39mTest failed but keep the grunt process alive.
```

See error in full build log at: https://s3.amazonaws.com/archive.travis-ci.org/jobs/83643870/log.txt

**Comment by lirantal** [comment]
@jloveland can you please take a look? since you've recently worked on the E2E tests in grunt/gulp

**Comment by jloveland** [comment]
I was having trouble with #965, so I closed and I submitted #968 as a separate PR

**Comment by codydaig** [comment]
@jloveland If the E2E tests fail, the build still passes:
https://travis-ci.org/codydaig/mean/jobs/85656775 
Intentionally broke a test to demonstrate the issue.

**Comment by jloveland** [comment]
@lirantal , there were 2 PRs that can resolve this bug:
#968 - MERGED - fixes the issue with selenium not starting
#993 - NEW - fixes configuration for grunt task to fail if e2e test fails which will fail the travis build

**Comment by codydaig** [comment]
thanks @jloveland

**Comment by lirantal** [comment]
Great thanks, I'll close this issue.
